# configs/dictionary.yaml

# --- Localization Dictionary ---
LOCALIZATION:
  en:
    title_report: "Stock Data Report"
    title_profile: "Company Profile"
    title_realtime: "Real-time Quote"
    title_chart: "Stock Price Chart"
    title_summary: "Historical Summary"
    header_generated: "Report Generated At"
    header_history: "Historical Data Range"
    label_name: "Company Name"
    label_industry: "Industry"
    label_list_date: "Listing Date"
    label_desc: "Description"
    label_latest_price: "Latest Price"
    label_open: "Open"
    label_high: "High"
    label_low: "Low"
    label_volume: "Volume (Shares)"
    missing_profile: "Failed to load company profile data."
    missing_realtime: "Failed to load real-time quote."
    missing_history: "No historical data available."
    chart_unavailable: "Price Trend (Chart Unavailable)"
    chart_note: "Something wrong;( Note: Install required libraries with: pip install matplotlib mplfinance"
    price_unit: "Price (USD)"
    no_description: "No description available"

  cn:
    title_report: "股票數據報告"
    title_profile: "公司簡介"
    title_realtime: "實時行情"
    title_chart: "股價走勢圖"
    title_summary: "歷史數據概覽"
    header_generated: "報告生成時間"
    header_history: "歷史數據區間"
    label_name: "公司名稱"
    label_industry: "行業"
    label_list_date: "上市日期"
    label_desc: "簡介"
    label_latest_price: "最新價格"
    label_open: "今開盤"
    label_high: "最高價"
    label_low: "最低價"
    label_volume: "交易量 (股)"
    missing_profile: "公司簡介數據獲取失敗"
    missing_realtime: "實時行情數據獲取失敗"
    missing_history: "無歷史數據"
    chart_unavailable: "股價走勢 (圖表不可用)"
    chart_note: "發生了一些錯誤0-0，或許您忘記了安裝依賴庫: pip install matplotlib mplfinance"
    price_unit: "價格 (元)"
    no_description: "無簡介信息"